workflows:
  android-workflow:
    environment:
      flutter: stable
    scripts:
      - flutter create .
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
